server:
  port: 8888

spring:
  application:
    name: config-server-01

  cloud:
    config:
      server:
        git:
          uri: https://github.com/czyoyo/config-data-01.git
          default-label: master
