server:
  port: 8888

spring:
  application:
    name: config-server-01

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  profiles:
    active: git # git, native, vault

  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/backend/config-repo
        git:
          uri: https://github.com/czyoyo/config-data-01.git
          default-label: master

management:
  endpoints:
    web:
      exposure:
        include: refresh, health
